# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  omniauth:
    tunnistamo:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      icon: account-login
      server_uri: <%= ENV["OMNIAUTH_TUNNISTAMO_SERVER_URI"] %>
      client_id: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_SECRET"] %>
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
  maps:
    api_key: <%= ENV["MAPS_API_KEY"] %>

development:
  <<: *default
  secret_key_base: db3906ab497d6d43915b880d96aa3ba983db320867725d4aee3233ffa79b1fb81b8c9f23fddbff03bd3d290b5181f3f9f98c0cbe5dfad7747784508de0c75cd4
  secret_key_devise: 2faa8ec33ed6a2e9ea448370ac036bc096b02634066a2bc9efc55f3f7a1084d7cda8cc99dd30ff7b0f3fa85275ccb9cf8c1a67e342c1bd38147a385d02fae279
  secret_key_jwt: 61c15e643565ff36d8f922290cd3d9620345f88779e58ca8a26ac0f8ed93f066d324b818a7ab3a034f8566e793f667774dfa725c7f72ab64cdea098414b93750
  omniauth:
    tunnistamo:
      enabled: true
      icon: account-login
      server_uri: <%= ENV["OMNIAUTH_TUNNISTAMO_SERVER_URI"] %>
      client_id: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_SECRET"] %>
  # azure_blob:
  #   container: baz
  #   host: biz # optional
  #   storage_access_key: bar
  #   storage_account_name: foo
  #   storage_blob_host: baz # optional

development_paahtimo:
  <<: *default
  secret_key_base: a15f0787855bb97b245002e23de28c0ab32615adbc3c8fdec88de1c5fa7e2763988c0cc1ae47c953ab896def2cc9da90f3156f705a53ee5da284bcded943b682
  secret_key_devise: c3f6e63fbc08dc13853fc7963ad824362fab5631073fe5fdea6a4eac3d201ccb7b0416cbb40371f8b5837a794ac14d6b8c99ed2a5b9dc8b125d21c85d4cca7ca
  secret_key_jwt: f12404c5d2333496189dc1b332c3048d74c9e170274a0e0acb3b54d3c7561e177c36872c7e4880e7fb189a12af4deea2bafb5fdb6878a2177786fa76afc34f24
  omniauth:
    tunnistamo:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: true
      server_uri: <%= ENV["OMNIAUTH_TUNNISTAMO_SERVER_URI"] %>
      client_id: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_SECRET"] %>

test:
  <<: *default
  secret_key_base: 0b0857276d7d187b0f3b5f77fc8e33c4be52b4efa3a1c178644831f7fb5fef7b947108edcca4c84003bb3ddb3f58db115e2f1d4d0cd82dded4568130baa8f7f0
  secret_key_devise: 2faa8ec33ed6a2e9ea448370ac036bc096b02634066a2bc9efc55f3f7a1084d7cda8cc99dd30ff7b0f3fa85275ccb9cf8c1a67e342c1bd38147a385d02fae279
  secret_key_jwt: 6041d61d5026b44664835730bbfbffd70260401d663422d9c000bcb208954db955446169d81399c8268efbf3b9bdc71cce91ab0bea73b8818a455c7e4ae99d2a
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

# Do not keep production or staging secrets in the repository,
# instead read values from the environment.

staging:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_devise: <%= ENV["SECRET_KEY_DEVISE"] %>
  secret_key_jwt: <%= ENV["SECRET_KEY_JWT"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
  omniauth:
    tunnistamo:
      enabled: true
      server_uri: <%= ENV["OMNIAUTH_TUNNISTAMO_SERVER_URI"] %>
      client_id: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_SECRET"] %>

staging_paahtimo:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_devise: <%= ENV["SECRET_KEY_DEVISE"] %>
  secret_key_jwt: <%= ENV["SECRET_KEY_JWT"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
  omniauth:
    tunnistamo:
      enabled: true
      server_uri: <%= ENV["OMNIAUTH_TUNNISTAMO_SERVER_URI"] %>
      client_id: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_SECRET"] %>

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_devise: <%= ENV["SECRET_KEY_DEVISE"] %>
  secret_key_jwt: <%= ENV["SECRET_KEY_JWT"] %>
  redis_host: <%= ENV["REDIS_HOST"] %>
  redis_port: <%= ENV["REDIS_PORT"] %>
  redis_pass: <%= ENV["REDIS_PASS"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
  omniauth:
    tunnistamo:
      enabled: true
      server_uri: <%= ENV["OMNIAUTH_TUNNISTAMO_SERVER_URI"] %>
      client_id: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_SECRET"] %>

production_paahtimo:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_devise: <%= ENV["SECRET_KEY_DEVISE"] %>
  secret_key_jwt: <%= ENV["SECRET_KEY_JWT"] %>
  redis_host: <%= ENV["REDIS_HOST"] %>
  redis_port: <%= ENV["REDIS_PORT"] %>
  redis_pass: <%= ENV["REDIS_PASS"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
  omniauth:
    tunnistamo:
      enabled: true
      server_uri: <%= ENV["OMNIAUTH_TUNNISTAMO_SERVER_URI"] %>
      client_id: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_TUNNISTAMO_CLIENT_SECRET"] %>
